spring.datasource:
  url: jdbc:postgresql://localhost:5432/EncounterBot
  username: postgres
  password: root
  driver-class-name: org.postgresql.Driver
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
url:
  path:
    monsterLibrary: http://localhost:8080/MonsterLibrary/getMonster/